### ISSUE TITLE
Inital padding revisions error

### ISSUE THREAD

**Issue by EdHarrisRedtail** [tonyduckles/svn2svn#18]
An excellent piece of work and is just what I needed for dis-tangling some projects out of a massive repo!

It all seems to work well under Cywin on my Windows machine.

One small error I think I've found is that the when preserving revision numbers, the first lot of padding if skipped, as you've used source_rev instead of source_start_rev and this meant the first commit from the source always went in as rev #1 in the destination and then there was a bunch of padding to get it back in step for the next commit. Diff file for the fix is:

```
--- C:/Temp/SVN Migration/svn2svn-master/svn2svn-master/svn2svn/run/svnreplay.py	Sat Sep 19 23:18:50 2015
+++ C:/Temp/SVN Migration/svn2svn-master/svn2svn-master/svn2svn/run/svnreplay - Copy.py	Fri Jan 22 10:33:35 2016
@@ -876,8 +876,8 @@ def real_main(args):
         source_start_rev = int(source_start_log['revision'])
         ui.status("Starting at source revision %s.", source_start_rev, level=ui.VERBOSE)
         ui.status("", level=ui.VERBOSE)
-        if options.keep_revnum and source_rev > target_rev_last:
-            target_rev_last = keep_revnum(source_rev, target_rev_last, wc_target_tmp)
+        if options.keep_revnum and source_start_rev > target_rev_last:
+            target_rev_last = keep_revnum(source_start_rev, target_rev_last, wc_target_tmp)
 
         # For the initial commit to the target URL, export all the contents from
         # the source URL at the start-revision
```

**Comment by tonyduckles** [comment]
Yep, that sounds right to me. Plus, this led me to find another place that was incorrectly using `source_rev` instead of `source_start_rev`. Thanks!

Fixed by 153cfc9.
