### ISSUE TITLE
invalid syntax on <>

### ISSUE THREAD

**Issue by johnmanko** [tonyduckles/svn2svn#26]
I'm getting a python error.  `my-project/trunk` does exist, but `my-project/trunk/my-lib` does not.

```
$ ./svnreplay.py --verbose --keep-author --keep-date --keep-prop file:///var/svn/my-lib/trunk file:///var/svn/my-project/trunk/my-lib
Traceback (most recent call last):
  File "./svnreplay.py", line 3, in <module>
    from svn2svn.run.svnreplay import main
  File "/var/svn/svn2svn/svn2svn/run/svnreplay.py", line 251
    is_diff = True if sum1 <> sum2 else False
                            ^
SyntaxError: invalid syntax
```

```
$ python --version
Python 3.4.6
```

**Comment by tonyduckles** [comment]
Try using Python 2.x.  All this code was written for Python 2.x, and Python 2.x vs Python 3.x aren't fully inter-compatible.

**Comment by johnmanko** [comment]
Thanks, @tonyduckles.  I'll give that a try now. I didn't bother to use v2 because the README says v2.6 or greater, and I assumed that also included v3.

UPDATE: v2.7 works.
